export const Path = {
    DASHBOARD: "/dashboard",
    MANAGE_ORDERS: "/manage-orders",
    MANAGE_RECIPES: "/manage-recipes",
    MANAGE_INGREDIENTS: "/manage-ingredients",
    MANAGE_DEVICES: "/manage-devices",
    MANAGE_KIOSKS: "/manage-kiosks",
    MANAGE_COSTS: "/manage-costs",
    MANAGE_PRODUCTS: "/manage-products",
    MANAGE_WORKFLOWS: "/manage-workflows",
    MANAGE_MENUS: "/manage-menus",
    MANAGE_ORGANIZATIONS: "/manage-organizations",
    MANAGE_STORES: "/manage-stores",
    PROFILE: "/profile",
    REMINDER: "/reminder",
    NOT_FOUND: "/not-found",
    RECIPE: "/recipe",
    HOME: "/",
    LOGIN: "/login",
    MENUS_DETAIL: "/manage-menus/:slug",
    MANAGE_LOCATION_TYPES: "/manage-location-types",
    MANAGE_DEVICE_TYPES: "/manage-device-types",
    MANAGE_DEVICE_MODELS: "/manage-device-models",
    MANAGE_KIOSK_VERSIONS: "/manage-kiosk-versions",
    MANAGE_KIOSK_TYPES: "/manage-kiosk-types",
    CREATE_ACCOUNT: "/create-account",
    CREATE_WORKFLOW: "/create-workflow",
};

